#!/usr/bin/env bash
#  script that transfers a file from our client to a server

# check if all 4 parameters are provided

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

#assign the variables parameters
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

#transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username"@"$ip":~/
