#!/usr/bin/env bash
# script that installs and configures HA-prozy on your lb-01 server
# '$aENABLED=1\n': this is the script to use for editing. $a means to append the text that follows to the end of the file. ENABLED=1 is the text to append, and \n is a newline character that will add a new line after the appended text.
# -e: specify a script to use for editing.
# -i: edit the file in place, i.e., modify the file directly.

# install HAproxy
sudo apt-get update
sudo apt-get -y install haproxy

# Open the HAproxy configuration file for editing
sudo nano /etc/haproxy/haproxy.cfg

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind *:80\n\tbalance roundrobin\n\tserver 178444-web-01 3.90.80.30:80 check\n\tserver 178444-web-02 100.25.180.71:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
