#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.

for numb in {1..100}
do
 if (( numb % 3 == 0 && numb % 5 == 0 ))
 then
   echo "FizzBuzz"
 elif (( numb % 3 == 0 ))
 then
   echo "Fizz"
 elif (( numb % 5 == 0 ))
 then
   echo "Buzz"
 else
   echo "$numb"
 fi
done
