#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine
# it's executed on

# Use ifconfig to get list of network interfaces and their IP addresses
ifconfig_output=$(ifconfig | grep 'inet addr')

# Parse ifconfig output to extract IPv4 addresses
ipv4_addresses=$(echo "$ifconfig_output" | awk '{print $2}' | cut -d ':' -f 2)

#print the list of IPv4 addresses
echo "$ipv4_addresses"
