#!/usr/bin/env bash
# configure ssh client to suite our needs
# and connect to a server without typing a password

Host *
   Hostname 18.204.13.231
   User ubuntu
   IdentityFile ~/.ssh/school
   PasswordAuthentication no
