#!/usr/bin/env bash
# configure ssh client to suite our needs
# and connect to a server without typing a password

Host *
   Hostname 54.160.125.144
   User ubuntu
   IdentityFile ~/.ssh/school
   PasswordAuthentication no
